import React from 'react';
import styled from 'styled-components';
import { useNavigate } from 'react-router-dom';

const InfoContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 40px;
  background-color: #1a1a1a;
  min-height: 100vh;
  color: white;
`;

const InfoHeader = styled.div`
  text-align: center;
  margin-bottom: 40px;
`;

const InfoTitle = styled.h1`
  font-size: 2.5rem;
  margin-bottom: 10px;
`;

const InfoDescription = styled.p`
  font-size: 1.2rem;
  color: #aaa;
`;

const InfoContent = styled.div`
  width: 100%;
  max-width: 800px;
  background-color: #2a2a2a;
  padding: 30px;
  border-radius: 8px;
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
`;

const Section = styled.div`
  margin-bottom: 30px;
`;

const SectionTitle = styled.h2`
  font-size: 1.8rem;
  margin-bottom: 15px;
  color: #e6e6e6;
  border-bottom: 2px solid #444;
  padding-bottom: 8px;
`;

const SectionContent = styled.div`
  font-size: 1.1rem;
  line-height: 1.6;
  color: #cccccc;
`;

const List = styled.ul`
  margin-left: 20px;
  margin-top: 10px;
  margin-bottom: 10px;
`;

const ListItem = styled.li`
  margin-bottom: 5px;
`;

const FactionTable = styled.div`
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  gap: 20px;
  margin-top: 20px;
`;

const FactionCard = styled.div<{ color: string }>`
  background-color: #333;
  border-left: 5px solid ${props => props.color};
  border-radius: 4px;
  padding: 15px;
`;

const FactionHeader = styled.div`
  display: flex;
  align-items: center;
  gap: 10px;
  margin-bottom: 15px;
`;

const FactionIcon = styled.div`
  font-size: 1.8rem;
`;

const FactionName = styled.h3`
  font-size: 1.5rem;
  margin: 0;
`;

const StructureList = styled.div`
  display: grid;
  gap: 8px;
`;

const Structure = styled.div`
  display: flex;
  align-items: center;
  gap: 8px;
  background-color: #444;
  padding: 8px;
  border-radius: 4px;
`;

const StructureSymbol = styled.div`
  font-weight: bold;
  font-size: 1.2rem;
  width: 25px;
  height: 25px;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #555;
  border-radius: 4px;
`;

const StructureDetails = styled.div`
  flex: 1;
`;

const StructureName = styled.div`
  font-weight: bold;
`;

const StructureDescription = styled.div`
  font-size: 0.9rem;
  color: #aaa;
`;

const BackToMenuButton = styled.button`
  position: absolute;
  top: 20px;
  left: 20px;
  background-color: transparent;
  border: none;
  color: #aaa;
  font-size: 1rem;
  cursor: pointer;
  display: flex;
  align-items: center;
  
  &:hover {
    color: white;
  }
  
  svg {
    margin-right: 8px;
  }
`;

const InfoButton = styled.button`
  padding: 12px 24px;
  background-color: #2196F3;
  color: white;
  border: none;
  border-radius: 4px;
  font-size: 1rem;
  cursor: pointer;
  transition: background-color 0.2s;
  margin-top: 20px;
  
  &:hover {
    background-color: #0b7dda;
  }
`;

const GameInfo: React.FC = () => {
  const navigate = useNavigate();
  
  return (
    <InfoContainer>
      <BackToMenuButton onClick={() => navigate('/')}>
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M19 12H5M5 12L12 19M5 12L12 5" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
        </svg>
        Back to Menu
      </BackToMenuButton>
      
      <InfoHeader>
        <InfoTitle>Game Information</InfoTitle>
        <InfoDescription>Everything you need to know about Wartiles Online</InfoDescription>
      </InfoHeader>
      
      <InfoContent>
        <Section>
          <SectionTitle>Game Overview</SectionTitle>
          <SectionContent>
            <p>
              Wartiles Online is a territory control strategy game where 2-3 players compete to dominate a 25x25 grid.
              Choose from three unique factions, manage your resources, and expand your territory strategically.
            </p>
            <p>
              The game ends when a player has either occupied all opponents' tiles or has the most tiles after 5 minutes.
            </p>
          </SectionContent>
        </Section>
        
        <Section>
          <SectionTitle>Resources</SectionTitle>
          <SectionContent>
            <p>There are two main resources in the game:</p>
            <List>
              <ListItem>
                <strong>Gold</strong> - Used to annex neutral tiles and occupy enemy tiles. Generated at a base rate that can be increased by building Gold-producing structures.
              </ListItem>
              <ListItem>
                <strong>Units</strong> - Used to occupy enemy tiles. The more units you have, the more territory you can capture. Generated by building Unit-producing structures.
              </ListItem>
            </List>
          </SectionContent>
        </Section>
        
        <Section>
          <SectionTitle>Gameplay</SectionTitle>
          <SectionContent>
            <List>
              <ListItem>
                <strong>Starting:</strong> Each player spawns with one tile placed randomly on the board.
              </ListItem>
              <ListItem>
                <strong>Annexing Tiles:</strong> You can annex neutral tiles adjacent to your territory by spending Gold.
              </ListItem>
              <ListItem>
                <strong>Occupying Enemy Tiles:</strong> To take over an enemy tile, you must spend both Gold and Units.
              </ListItem>
              <ListItem>
                <strong>Building Structures:</strong> You can build one structure per tile to increase your resource generation or defense.
              </ListItem>
              <ListItem>
                <strong>Victory:</strong> Win by having the most tiles after 5 minutes or by occupying all enemy tiles.
              </ListItem>
            </List>
          </SectionContent>
        </Section>
        
        <Section>
          <SectionTitle>Factions</SectionTitle>
          <SectionContent>
            <p>Each faction has unique structures that provide different bonuses:</p>
            
            <FactionTable>
              <FactionCard color="#4169E1">
                <FactionHeader>
                  <FactionIcon>👨‍🚀</FactionIcon>
                  <FactionName>Humans</FactionName>
                </FactionHeader>
                <StructureList>
                  <Structure>
                    <StructureSymbol>G</StructureSymbol>
                    <StructureDetails>
                      <StructureName>Farm</StructureName>
                      <StructureDescription>Generates gold over time</StructureDescription>
                    </StructureDetails>
                  </Structure>
                  <Structure>
                    <StructureSymbol>U</StructureSymbol>
                    <StructureDetails>
                      <StructureName>Barracks</StructureName>
                      <StructureDescription>Generates units over time</StructureDescription>
                    </StructureDetails>
                  </Structure>
                  <Structure>
                    <StructureSymbol>D</StructureSymbol>
                    <StructureDetails>
                      <StructureName>Fort</StructureName>
                      <StructureDescription>Increases defence of the tile</StructureDescription>
                    </StructureDetails>
                  </Structure>
                </StructureList>
              </FactionCard>
              
              <FactionCard color="#B22222">
                <FactionHeader>
                  <FactionIcon>🤖</FactionIcon>
                  <FactionName>Robots</FactionName>
                </FactionHeader>
                <StructureList>
                  <Structure>
                    <StructureSymbol>G</StructureSymbol>
                    <StructureDetails>
                      <StructureName>Network</StructureName>
                      <StructureDescription>Generates gold over time</StructureDescription>
                    </StructureDetails>
                  </Structure>
                  <Structure>
                    <StructureSymbol>U</StructureSymbol>
                    <StructureDetails>
                      <StructureName>Factory</StructureName>
                      <StructureDescription>Generates units over time</StructureDescription>
                    </StructureDetails>
                  </Structure>
                  <Structure>
                    <StructureSymbol>D</StructureSymbol>
                    <StructureDetails>
                      <StructureName>Autoturret</StructureName>
                      <StructureDescription>Increases defence of the tile</StructureDescription>
                    </StructureDetails>
                  </Structure>
                </StructureList>
              </FactionCard>
              
              <FactionCard color="#228B22">
                <FactionHeader>
                  <FactionIcon>👾</FactionIcon>
                  <FactionName>Aliens</FactionName>
                </FactionHeader>
                <StructureList>
                  <Structure>
                    <StructureSymbol>G</StructureSymbol>
                    <StructureDetails>
                      <StructureName>Hive</StructureName>
                      <StructureDescription>Generates gold over time</StructureDescription>
                    </StructureDetails>
                  </Structure>
                  <Structure>
                    <StructureSymbol>U</StructureSymbol>
                    <StructureDetails>
                      <StructureName>Nest</StructureName>
                      <StructureDescription>Generates units over time</StructureDescription>
                    </StructureDetails>
                  </Structure>
                  <Structure>
                    <StructureSymbol>D</StructureSymbol>
                    <StructureDetails>
                      <StructureName>Biowall</StructureName>
                      <StructureDescription>Increases defence of the tile</StructureDescription>
                    </StructureDetails>
                  </Structure>
                </StructureList>
              </FactionCard>
            </FactionTable>
            
            <p style={{ marginTop: '20px' }}>
              <strong>Special Note:</strong> Unlike the other factions, Aliens start with a base unit production rate of 1 unit per second.
            </p>
          </SectionContent>
        </Section>
        
        <Section>
          <SectionTitle>Game Modes</SectionTitle>
          <SectionContent>
            <List>
              <ListItem>
                <strong>Multiplayer:</strong> Play with up to 3 players in a competitive match.
              </ListItem>
              <ListItem>
                <strong>Solo:</strong> Play against AI opponents with adjustable difficulty.
              </ListItem>
            </List>
          </SectionContent>
        </Section>
        
        <InfoButton onClick={() => navigate('/')}>Back to Main Menu</InfoButton>
      </InfoContent>
    </InfoContainer>
  );
};

export default GameInfo; 